import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar"
import Form from "../components/Form"
import Splash from "../components/Splash"
import { RecoilRoot, atom, useRecoilState} from 'recoil'

// Atoms
export const formState = atom({
  key: 'formState', // unique ID (with respect to other atoms/selectors)
  default: 'basketball', // default value (aka initial value)
});

export default function Home() {
  return (
    <RecoilRoot>
      <Head>
        <title>BSQ Facility Registration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* MAIN CONTENT */}
      <main className={styles.main}>
        <Splash />
        <Navbar />
        <Form />
        
      </main>
    </RecoilRoot>
  )
}
